mod

diff --git a/.github/workflows/web_scenario.yml b/.github/workflows/web_scenario.yml
--- a/.github/workflows/web_scenario.yml
+++ b/.github/workflows/web_scenario.yml
@@ -63,7 +63,7 @@ jobs:
         # テスト実行時にも環境変数を設定
         #   VITE_MOCK_API: "true"
         #   VITE_API_HOST: "http://localhost:1323/api/v1"
-        run: npm test tests/Account.spec.ts || true # Continue even if tests fail
+        run: npm test tests/Account.spec.ts tests/Projects.spec.ts || true # Continue even if tests fail
 
       - name: Upload test results and screenshots
         uses: actions/upload-artifact@v4
